export const ROOT_PATH = '/'
export const USER_SIGN_IN_PATH = '/users/sign-in'
export const USER_SIGN_UP_PATH = '/users/sign-up'
export const CHAT_PATH = '/chat'
export const SCRABBLE_PATH = '/games/:gameId'
